name: Deploy

on:
  push: 
  # this is because this repo is a template. upon creating a new repo this CI must be not triggered, it is just meant for the template itself
    branches-ignore: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/
          scope: "@nexys-system"
      - run: yarn
      - run: yarn test
      - name: Build page
        run: SNOWPACK_PUBLIC_URL=/boilerplate-app-min SNOWPACK_PUBLIC_GIT_SHA=$GITHUB_SHA SNOWPACK_PUBLIC_VERSION=${GITHUB_REF##*/} yarn buildAll
      - name: add 404
        run: cp build/index.html build/404.html
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./build
