name: Publish

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 17
          registry-url: https://npm.pkg.github.com/
      - run: yarn
      - run: yarn test
      - name: Build page
        run: SNOWPACK_PUBLIC_WITH_BACKEND=true SNOWPACK_PUBLIC_URL= SNOWPACK_PUBLIC_GIT_SHA=$GITHUB_SHA SNOWPACK_PUBLIC_VERSION=${GITHUB_REF##*/} yarn buildAll
      - name: Publish package
        run: |
          echo "registry=https://npm.pkg.github.com/" >> .npmrc 
          cat .npmrc
          NODE_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }} npm publish
